name: ${name}
version: ${version}
description: Enchantment Tweaks
author: acomputerdog
main: net.acomputerdog.enchanttweaks.PluginEnchantTweaks
api-version: 1.13

commands:
  unenchant:
    description: Split enchantments off of an item
    permission: enchanttweaks.unenchant
    usage: Incorrect usage!  Use /unenchant
    aliases: [enchantstrip, deenchant, stripenchant, stripenchants]

permissions:
  enchanttweaks.unenchant:
    description: Use /unenchant
    default: true